docs(api-admin): add delete user method description | openapi docs
accesso-app/backend pull request #36
Opened 2021-06-24 11:55 UTC by asvtsv

Описание контракта для ручки Удаление пользователя из приложения. Задача -> https://linear.app/atomix/issue/ACC-62/udalenie-polzovatelya-iz-prilozheniya

2021-06-24 12:31 UTC, sergeysova requested changes
Проверь пожалуйста весь метод на соответствие формату:

https://t.me/c/1212987562/2269

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +  "/user/delete":
Так это удаление пользователя, а не удаление пользователя из приложения.

```suggestion
  "/applications/user.remove":
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +      operationId: userDeleteRequest
```suggestion
      operationId: applicationsUserRemove
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +      tags: [ User, Delete ]
```suggestion
      tags: [Applications]
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +        $ref: "#/components/requestBodies/UserDelete"
```suggestion
        $ref: "#/components/requestBodies/ApplicationUserRemove"
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +          $ref: "#/components/responses/UserDeletFailure"
```suggestion
        400:
          $ref: "#/components/responses/ApplicationUserRemoveFailure"
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +              error:
```suggestion
              code:
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +                  - server_error
```suggestion
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +                  - client_not_found
```suggestion
                  - application_not_found
```

2021-06-24 12:31 UTC, sergeysova commented on api-admin/openapi.yaml
> +                  - unauthenticated_user
access_denied и unauthorised_user это не одно и то же?

2021-06-24 15:57 UTC, asvtsv commented on api-admin/openapi.yaml
> +                  - unauthenticated_user
В моем понимание access_denied - это когда недостаточно прав, а unauthenticated_user - это когда например у пользователя протухла сессия, а он кидает запрос

2021-06-25 14:28 UTC, sergeysova requested changes

2021-06-25 14:28 UTC, sergeysova commented on api-admin/openapi.yaml
> +                description: It is the flag which say that user was deleted or something went wrong duiring delete proccess.
Будет ли ситуация, когда сервер отвечает 200 но здесь стоит false?
Вроде же все ошибки описаны в статусе 400.

Думаю здесь нужно просто пустой объект возвращать

2021-06-25 14:28 UTC, sergeysova commented on api-admin/openapi.yaml
> +              - error
```suggestion
              - code
```

2021-06-25 14:28 UTC, sergeysova commented on api-admin/openapi.yaml
> +                  - unauthorized_client
Кажется этой ошибки быть не может

2021-06-25 14:28 UTC, sergeysova commented on api-admin/openapi.yaml
> +              redirectUri:
Лишнее поле

2021-06-25 14:28 UTC, sergeysova commented on api-admin/openapi.yaml
> +              state:
Это тоже

2021-06-25 19:45 UTC, asvtsv commented on api-admin/openapi.yaml
> +                description: It is the flag which say that user was deleted or something went wrong duiring delete proccess.
Ответ показывает как прошел процесс удаления. Ну то есть удалось удалить пользователя или нет, а ошибки скорее говорят об инфраструктурных проблемах, так что в принципе можно получить ответ 200, но success: false

2021-06-25 20:11 UTC, asvtsv commented on api-admin/openapi.yaml
> +                  - unauthorized_client
Думаю что можно действительно объединить все в одну все-таки и оставить только `access_denied`

2021-06-25 20:24 UTC, asvtsv commented on api-admin/openapi.yaml
> +              redirectUri:
Идея в том, чтобы с бэка присылать страницу на которую нужно редиректнуться

2021-06-26 15:10 UTC, sergeysova commented on api-admin/openapi.yaml
> +                description: It is the flag which say that user was deleted or something went wrong duiring delete proccess.
Это не корректно. Если не удалось удалить, то это ошибка. 400 это ошибка бизнес-логики

2021-06-26 15:10 UTC, sergeysova commented on api-admin/openapi.yaml
> +              redirectUri:
Так а зачем? Это поле нужно только в OAuth2 процессе

2021-06-26 18:12 UTC, sergeysova approved these changes

2021-06-26 18:13 UTC, merged