docs(api-admin): add register application method description | openapi docs
accesso-app/backend pull request #38
Opened 2021-06-24 19:13 UTC by asvtsv

resolve https://linear.app/atomix/issue/ACC-57/sozdanie-novogo-prilozheniya

2021-06-26 15:05 UTC, sergeysova requested changes

2021-06-26 15:05 UTC, sergeysova commented on api-admin/openapi.yaml
> +  "/applications.registration":
```suggestion
  "/applications.create":
```
Я думаю есть разница между регистрацией и созданием. Мне кажется будут конфликты именований, между регистрацией В приложении и регистрацией приложения

2021-06-26 15:05 UTC, sergeysova commented on api-admin/openapi.yaml
> +      operationId: appReg
Не сокращай имена, пожалуйста

2021-06-26 15:05 UTC, sergeysova commented on api-admin/openapi.yaml
> +    AppRegDone:
И тут тоже

2021-06-26 15:05 UTC, sergeysova commented on api-admin/openapi.yaml
> +              appId:
При регистрации нельзя указать id, он будет сгенерен автоматом, как и все ключи.
А вот title, redirect URIs и флаг разрешения регистраций точно нужны

2021-06-27 12:12 UTC, asvtsv commented on api-admin/openapi.yaml
> +              appId:
Это ведь респонс. Но думаю что appKey - тут будет лишним

2021-07-02 12:41 UTC, Drevoed commented on api-admin/openapi.yaml
> +              appId:
Тут все норм же, респонс ведь

2021-07-02 12:41 UTC, Drevoed approved these changes

2021-07-07 07:43 UTC, sergeysova requested changes

2021-07-07 07:43 UTC, sergeysova commented on api-admin/openapi.yaml
> +              - requireRegistration
```suggestion
              - allowRegistrations
```

2021-07-07 07:43 UTC, sergeysova commented on api-admin/openapi.yaml
> +              requireRegistration:
```suggestion
              allowRegistrations:
```

2021-07-07 07:43 UTC, sergeysova commented on api-admin/openapi.yaml
>                - appId
```suggestion
              - applicationId
```

2021-07-07 07:43 UTC, sergeysova commented on api-admin/openapi.yaml
>                appId:
```suggestion
              applicationId:
```

2021-07-07 07:43 UTC, sergeysova approved these changes

2021-07-07 07:48 UTC, merged