ACC-47 add user_registrations to access_tokens
accesso-app/backend pull request #49
Opened 2021-07-10 08:34 UTC by sergeysova

2021-07-10 13:34 UTC, Drevoed requested changes

2021-07-10 13:34 UTC, Drevoed commented on core/src/contracts/mod.rs
>  impl<T> Repository for T where
С этим по-любому надо будет что-то сделать, а то vtable разрастется и диспатч будет совсем медленынй

Надо пробенчить, в тудушку

2021-07-10 13:34 UTC, Drevoed commented on core/src/contracts/mod.rs
>  impl<T> Repository for T where
С этим по-любому надо будет что-то сделать, а то vtable разрастется и диспатч будет совсем медленный

Надо пробенчить, в тудушку

2021-07-10 13:34 UTC, Drevoed commented on core/src/lib.rs
> +// #![deny(warnings)]
Включить бы обратно

2021-07-10 13:34 UTC, Drevoed commented on db/src/lib.rs
> +// #![deny(warnings)]
Тоже включить

2021-07-10 13:34 UTC, Drevoed commented on db/src/repos/session.rs
> +            SELECT users.*
Зачем *?

2021-07-10 13:34 UTC, Drevoed commented on db/src/repos/session.rs
> +            SELECT users.*
тот же вопрос

2021-07-10 13:34 UTC, Drevoed commented on db/src/repos/session.rs
> +            .fetch_one(&self.pool)
это rustfmt так отформатировал?

2021-07-10 13:34 UTC, Drevoed commented on db/src/repos/session.rs
> +                VALUES ($1, $2, $3)
Откуда такое форматирование?

2021-07-11 15:54 UTC, sergeysova commented on db/src/repos/session.rs
> +            SELECT users.*
Чтобы выбирать все поля не указывая рутинно каждое в отдельности

2021-07-11 15:54 UTC, sergeysova commented on db/src/repos/session.rs
> +                VALUES ($1, $2, $3)
Мб из моих рук

2021-07-11 16:21 UTC, sergeysova commented on db/src/repos/session.rs
> +            .fetch_one(&self.pool)
ага

2021-07-11 16:44 UTC, merged